SocketDatagrama.o: PaqueteDatagrama.hpp SocketDatagrama.hpp SocketDatagrama.cpp
	g++ -c SocketDatagrama.cpp
PaqueteDatagrama.o: PaqueteDatagrama.cpp PaqueteDatagrama.hpp
	g++ -c PaqueteDatagrama.cpp
clean:
	rm *.o