all: Hilos1 Hilos2 Hilos3

Hilos1: programa12-1.c
	gcc programa12-1.c -pthread -o Hilos1
Hilos2: programa12-2.c
	gcc programa12-2.c -pthread -o Hilos2
Hilos3: programa12-3.c
	gcc programa12-3.c -pthread -o Hilos3
clean:
	rm Hilos1 Hilos2 Hilos3

