prac_compo: prac_compo.cpp PoligonoIrreg.o
	g++ prac_compo.cpp PoligonoIrreg.o Coordenada.o -o prac_compo
PoligonoIrreg.o: PoligonoIrreg.cpp Coordenada.o PoligonoIrreg.h
	g++ PoligonoIrreg.cpp -c
Coordenada.o: Coordenada.cpp Coordenada.h
	g++ Coordenada.cpp -c