/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "oper.h"

struct Operandos *
suma_1_svc(struct Operandos *argp, struct svc_req *rqstp)
{
	static struct Operandos  result;

	result.i = (*argp).i + (*argp).j;

	return &result;
}

struct Operandos *
producto_1_svc(struct Operandos *argp, struct svc_req *rqstp)
{
	static struct Operandos  result;

	result.i = (*argp).i * (*argp).j;

	return &result;
}

struct Operandos *
cociente_1_svc(struct Operandos *argp, struct svc_req *rqstp)
{
	static struct Operandos  result;

	result.i = (*argp).i / (*argp).j;

	return &result;
}
