/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _OPER_H_RPCGEN
#define _OPER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Operandos {
	float i;
	float j;
};
typedef struct Operandos Operandos;

#define OPER_PROG 0x31111111
#define OPER_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define suma 1
extern  struct Operandos * suma_1(struct Operandos *, CLIENT *);
extern  struct Operandos * suma_1_svc(struct Operandos *, struct svc_req *);
#define producto 2
extern  struct Operandos * producto_1(struct Operandos *, CLIENT *);
extern  struct Operandos * producto_1_svc(struct Operandos *, struct svc_req *);
#define cociente 3
extern  struct Operandos * cociente_1(struct Operandos *, CLIENT *);
extern  struct Operandos * cociente_1_svc(struct Operandos *, struct svc_req *);
extern int oper_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define suma 1
extern  struct Operandos * suma_1();
extern  struct Operandos * suma_1_svc();
#define producto 2
extern  struct Operandos * producto_1();
extern  struct Operandos * producto_1_svc();
#define cociente 3
extern  struct Operandos * cociente_1();
extern  struct Operandos * cociente_1_svc();
extern int oper_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Operandos (XDR *, Operandos*);

#else /* K&R C */
extern bool_t xdr_Operandos ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_OPER_H_RPCGEN */
